---
title: "AI in Dentistry "
author: "Cara Yijin Zou"
date: "2025-12-18"
draft: true
tags: ["Bioinformatics", "Computer Science", "Artificial Intelligence", "Dentistry"]
categories: ["Dentistry", "Computer Science"]
output: html_document
summary: "Use of Artifical Intelligence in Dentistry" 

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Artificial intelligence has been exploding and integrating in all parts of life including in dentistry. It has applications in various areas such as radiographic interpretation, treatment planning, intraoral scanning/prosthetic design, practice management/operations, and patient communication. It can be a useful aid in dentistry, but it of course does not replace the expertise of dental professionals!


## Radiographic interpretation 
Many AI systems are now used to identify caries, bone loss, periapical radiolucencies, etc. Now how does this work? It takes real annotations from dentists to train models that are used to recognize patterns. No, the machine cannot diagnose BUT it does find similarities in the images provided to train it. Of course, the larger the training sample, the more accurate it should be. 



## References
1. AN INTRODUCTION TO BIOINFORMATICS ALGORITHMS, NEIL C. JONES AND PAVEL A. PEVZNER
2. http://data-science-sequencing.github.io/Win2018/lectures/lecture6/#:~:text=The%20greedy%20algorithm%20assembles%20the%20reads%20into%20an%20incorrect%20DNA,greedy%20approach%20can%20still%20fail.&text=One%20can%20think%20of%20the,looking%20for%20length%2D%E2%84%93%20overlaps.
3. https://ocw.mit.edu/courses/biology/7-91j-foundations-of-computational-and-systems-biology-spring-2014/lecture-slides/MIT7_91JS14_Lecture6.pdf